services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - ./dockerfiles/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./dockerfiles/mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: compass_assignment
    ports:
      - "43306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "127.0.0.1:48080:80"
    volumes:
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: openjdk:11-slim
    container_name: java-app
    ports:
      - 8080:8080
    tty: true
    # volumes:
    #   - ./server/src:/usr/src:cached